# Generated by Django 5.1.7 on 2025-03-17 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Milk Tea'), ('BL', 'Black Tea'), ('GT', 'Green Tea'), ('HT', 'Herbal Tea')], default='ML', max_length=2)),
            ],
        ),
    ]
