# Generated by Django 5.1.7 on 2025-03-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZodApp', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivariety',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
